# Generated by Django 2.2 on 2024-05-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20240508_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Mobile',
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
