# Generated by Django 2.2 on 2024-05-09 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20240509_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='State',
            new_name='state',
        ),
    ]
