# Generated by Django 2.2 on 2024-05-10 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20240509_2159'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='category',
        #     old_name='svg',
        #     new_name='info',
        # ),
        # migrations.RenameField(
        #     model_name='order',
        #     old_name='info',
        #     new_name='note',
        # ),
        # migrations.RenameField(
        #     model_name='order',
        #     old_name='nums',
        #     new_name='nums2',
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='address',
        #     field=models.CharField(blank=True, default='', max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='order',
        #     name='phone',
        #     field=models.CharField(blank=True, default='', max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='phone',
        #     field=models.CharField(blank=True, default='', max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='user',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
    ]
